### ISSUE TITLE
dead links on README.md

### ISSUE THREAD

**Issue by petrrr** [Sk-iRODS-Extensions/EMC-Isilon-Resource-Plugin-for-iRODS#1]
The following links in section [*External docs*](https://github.com/Sk-iRODS-Extensions/EMC-Isilon-Resource-Plugin-for-iRODS#external-docs) cannot be obtained and a 404 is returned:

 * https://irods.org/wp-content/uploads/2015/09/UMG2015_P.pdf
 * https://irods.org/wp-content/uploads/2015/06/Combes-iRODSResourceDrivers.pdf

Would be great if this could be fixed, as I am very interested to understand more.

**Comment by AndreyNevolin** [comment]
Hi @petrrr 

Thank you for reporting that! Now it's fixed: 9336326
